### ISSUE TITLE
Assignment - Week 4

### ISSUE THREAD

**Issue by dawnlwoodard** [NatanelHa/Ha-Hector-Internship#3]
1.  Running hector with RCP8.5, explore the change in the distribution of carbon across all of Hector’s carbon pools by 2100 from the present day. In other words - how much carbon is in each pool in 2100 compared to how much was in them in present day? Make a summary plot (or a few) to illustrate this. 
- Hint: strings for all the carbon pool variables in Hector are: ATMOSPHERIC_CO2(), SOIL_C(), VEG_C(), DETRITUS_C(), and OCEAN_C()
2. Also with RCP8.5, look at how the *rate* of change of carbon in each pool different between 2100 and present day. In other words, how have the net fluxes (the sum of all fluxes going out and all fluxes coming in) for Hector’s carbon pools changed between those time periods? For this question, treat land as one pool, rather than separated into soil, vegetation, and detritus. 
- Hint: net flux variables for ocean and land are: OCEAN_CFLUX(), LAND_CFLUX(). The atmospheric net flux is the sum of the fossil fuel emissions flux (FFI_EMISSIONS()) minus the ocean and land fluxes. 
3. Pick a different scenario and see how your answers to 1) and 2) change under this scenario.
4. (this one is just if you get through with 1-3 and have time to spare) By adjusting either or both of Hector’s two main parameters that control the carbon uptake and release of carbon on land, can you get the net atmosphere flux below 0.5 Pg C/yr in 2100? See how close you can keep the parameters to their original values and still meet the goal. Try this for RCP4.5 and RCP8.5. Relevant parameters are: BETA(), which affects carbon uptake (higher=more uptake), and Q10_RH(), which affects release of carbon from the land (higher=more emissions). 
5. Put all your results into an R-markdown file to share with Ben and me.

**Comment by NatanelHa** [comment]
I believe I have completed this assignment, and have created a comprehensive RMarkdown file. I'm happy to discuss anything about it whenever. 

For now, my plan is start to work on the quick presentation for Ms. Bosse, and if I have more time I'll continue to experiment with Hector. Let me know if there is something else you would like me working on before we meet again since I am now done with this assignment?
