### ISSUE TITLE
New week and new scenarios

### ISSUE THREAD

**Issue by bpbond** [NatanelHa/Ha-Hector-Internship#4]
- [x] Slides for meeting with Ms Bosse (you sent, we will provide feedback).
- [x] Symposium abstract (you sent, we will provide feedback). Submit revised abstract to Information Release.
- [x] Try constructing an 'alternate' scenario based on one of the RCPs and running it. To start, maybe the alternate is exactly the same exact for a one-year FFI (fossil fuel and industrial) pulse of 3x in the year 2050, for example. Compare them in a graph.
- [x] Begin to construct alternate scenario based on Jay's data. To begin with, I would suggest just focus on FFI emissions and the CCS uptake terms. I haven't look at this data yet so don't have a good sense of what this will entail.
- [x] Try the carbon tracking capability! This will involve switching to the `land_models` (v3) branch, build and install, and then run a scenario with that `trackingDate` parameter set. Not sure about how to read the resulting output file into R...explore, I am happy to help. Keep in mind this is an in-development branch so there may be rough edges.

Thanks! @dawnlwoodard any comments?

**Comment by dawnlwoodard** [comment]
Looks good to me!

**Comment by bpbond** [comment]
Looking at Jay's file:

* Filter world Region=="World"
* We'd like to end up with one INI file per scenario, but START WITH JUST ONE SCENARIO [or maybe two per Dawn's comment]
* You will need to reshape the data to long form, fill in missing years (e.g. using `dplyr::complete()` and then interpolate to annual values (using R's `approx()`)
* Hector's development branch has emissions (earth -> atmosphere) and anti-emissions (atmosphere -> earth)
* Hector's emissions time series should be "Emissions|CO2"; careful about units, probably need conversion!
* The anti-emissions t.s. is from "Carbon Sequestration|Direct Air Capture"
* Final step for each scenario: reshape so that "emissions" is in one column and "DAC" is a second

**Comment by NatanelHa** [comment]
I've finished everything on this list and so I'm closing this issue now! Sorry I'm closing it later than I probably should've. 

I have been able to successfully create tracking plots and also create scenarios based on Jay's data. This morning, with the branches merged, I have been able create tracking plots from Jay's scenarios. I will continue working on that for now! 

Thanks, 
Natanel
